version: '3'
services:
  server:
    build:
      context: .
    image: ralliotta:latest
    ports:
      - "8088:80"
      - "8089:8089"
    volumes:
      - ./assets:/app/assets
      - ./templates:/app/templates
      - ./bin:/app/bin
    environment:  
      - SUPPRESS_SUPPORT=1

