version: '3'
services:
  server:
    build:
      context: .
    image: rally2:latest
    ports:
      - "8000:80"
      - "8088:8088"
    volumes:
      - ./assets:/app/assets
      - ./templates:/app/templates
    environment:  
      - LOCAL=1

